# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

steps:
- script: dotnet restore
- script: dotnet build
  displayName: 'Run a one-line script'

pool:
  vmImage: 'ubuntu-latest'


